In [665]:

# Loading some libraries
import pandas as pd


#pd.options.display.max_columns = None
#pd.options.display.max_rows = None

# 1. Loading The Data

In [666]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [667]:
raw_csv_data.head(5)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [668]:
# We must always make a copy of our initial dataset
df = raw_csv_data.copy()

In [669]:
df.head(4)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4

In [670]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


# 2. Data preprocessing

In [671]:
# Drop the ID columns because it is a nominal data and it is not carrying any information.

df = df.drop(['ID'], axis=1)


In [672]:
df.head(2)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   

   Absenteeism Time in Hours  
0                          4  
1                          0

### Analyzing The Reasons for Absence

In [673]:
# Analyzing The Reasons for Absence

df['Reason for Absence'].head(4)

0    26
1     0
2    23
3     7
Name: Reason for Absence, dtype: int64

In [674]:
df['Reason for Absence'].min()

0

In [675]:
df['Reason for Absence'].max()

28

In [676]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [677]:
# An other method
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [678]:
len(df['Reason for Absence'].unique())

28

### Obtaining Dummies from a Single Feature

In [679]:
# Get Dummies
reason_columns = pd.get_dummies(df['Reason for Absence'])

In [680]:
reason_columns.head(5)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   19  21  22  23  24  25  26  27  28  
0   0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0   0  
2   0   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0   0  
4   0   0   0   1   0   0   0   0   0

In [681]:
# Checking a missing values
reason_columns['check'] = reason_columns.sum(axis=1) 
# If we get 0 = missimg values, 1 = single value
reason_columns.head(5)

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  \
0  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
1  1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   

   22  23  24  25  26  27  28  check  
0   0   0   0   0   1   0   0      1  
1   0   0   0   0   0   0   0      1  
2   0   1   0   0   0   0   0      1  
3   0   0   0   0   0   0   0      1  
4   0   1   0   0   0   0   0      1

In [682]:
reason_columns['check'].sum(axis=0) 

700

In [683]:
reason_columns['check'].unique()

array([1], dtype=int64)

In [684]:
# Let's drop the check columns
reason_columns = reason_columns.drop(['check'], axis=1)
reason_columns.head(4)

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  \
0  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
1  1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   

   22  23  24  25  26  27  28  
0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0  
2   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0

In [685]:
# Drop Reason 0 to avoid potential multicollinearity issues
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True)
reason_columns.head(4)

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   

   21  22  23  24  25  26  27  28  
0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0  
2   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0

### Group the Reasons for Absence

In [686]:
# Group the Reasons for Absence

df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [687]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

In [688]:
# Step 1 : Drop the Reason for Absence from the df
df = df.drop(['Reason for Absence'], axis=1)
df.head(4)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4

In [689]:
# Step 2 : Grouping the variables

# Classifying the various Reasons for Absence

reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:28].max(axis=1)

In [690]:
# Step 3 : Concatenate Columns Values

df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis=1)
df.head(4)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0

In [691]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [692]:
# Rename the colmns 0, 1, 2 and 3 to Reason_1, Reason_2, Reason_3, Reason_4

columns_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [693]:
df.columns = columns_names

In [694]:
df.head(4)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0

### Reoder Columns

In [695]:
columns_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [696]:
df = df[columns_names_reordered]

In [697]:
df.head(4)

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4

### Create Checkpoint

In [698]:
# Create a copy of the current state of the df DataFrame
df_reason_mod = df.copy()

In [699]:
df_reason_mod.head(3)

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2

### Date Feature Preprocessing

In [700]:
df_reason_mod['Date'].head(4)

0    07/07/2015
1    14/07/2015
2    15/07/2015
3    16/07/2015
Name: Date, dtype: object

In [701]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format='%d/%m/%Y')

In [702]:
df_reason_mod['Date'].head(4)

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
Name: Date, dtype: datetime64[ns]

In [703]:
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [704]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Reason_1                   700 non-null    uint8         
 1   Reason_2                   700 non-null    uint8         
 2   Reason_3                   700 non-null    uint8         
 3   Reason_4                   700 non-null    uint8         
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64         
 6   Distance to Work           700 non-null    int64         
 7   Age                        700 non-null    int64         
 8   Daily Work Load Average    700 non-null    float64       
 9   Body Mass Index            700 non-null    int64         
 10  Education                  700 non-null    int64         
 11  Children                   700 non-null    int64         
 12  Pets    

### Extract the Month Value

In [705]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [706]:
df_reason_mod['Date'][0].month
#7 = July, Note that here, Months take values from 1 to 12

7

In [707]:
list_months = []
list_months

[]

In [708]:
df_reason_mod.shape

(700, 14)

In [709]:
''' for i in range(700):
    list_months.append(df_reason_mod['Date'][i].month)
     '''
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [710]:
list_months
len(list_months)

700

In [711]:
df_reason_mod['Montth Value'] = list_months

In [712]:
df_reason_mod.head(4)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   

   Children  Pets  Absenteeism Time in Hours  Montth Value  
0         2     1                          4             7  
1         1     0                          0             7  
2         0     0                          2             7  
3         2     0                          4             7

### Extract the Day of the Week

In [713]:
df_reason_mod['Date'][699].weekday()

3

In [714]:
df_reason_mod['Date'][699] # 2018-05-31 was Thursday

Timestamp('2018-05-31 00:00:00')

In [715]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [716]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [717]:
df_reason_mod.head(4)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   

   Children  Pets  Absenteeism Time in Hours  Montth Value  Day of the Week  
0         2     1                          4             7                1  
1         1     0                          0             7                1  
2         0     0                          2             7                2  
3         2     0                          4             7                3

In [718]:
df_reason_data_mod = df_reason_mod.copy()

In [719]:
df_reason_data_mod.head(4)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   

   Children  Pets  Absenteeism Time in Hours  Montth Value  Day of the Week  
0         2     1                          4             7                1  
1         1     0                          0             7                1  
2         0     0                          2             7                2  
3         2     0                          4             7                3

### Analyzing Several Straightforward Columns for this projects

In [720]:
type(df_reason_data_mod['Transportation Expense'][0])

numpy.int64

In [721]:
type(df_reason_data_mod['Distance to Work'][0])

numpy.int64

In [722]:
type(df_reason_data_mod['Age'][0])

numpy.int64

In [723]:
type(df_reason_data_mod['Daily Work Load Average'][0])

numpy.float64

In [724]:
type(df_reason_data_mod['Body Mass Index'][0])

numpy.int64

### Working on Education, Children and Pets 


In [725]:
# Educatio is categorical data and contains integers

# We have to transform Education into dummy variable

In [726]:
df_reason_data_mod['Education'].unique()
# 1 = high school
# 2 = graduate
# 3 = postgraduate
# 4 = a master or doctor

array([1, 3, 2, 4], dtype=int64)

In [727]:
df_reason_data_mod['Education'].value_counts()
# 583 have high level, 
# 73 have graduate level
# 40 have postgraduate level
# 4 have a master or doctor

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [728]:
# Therefore, we can combine graduate, postgraduate and master or doctor in a single category
df_reason_data_mod['Education'] = df_reason_data_mod['Education'].map({
    1 : 0,
    2 : 1,
    3 : 1,
    4 : 1
})

In [729]:
df_reason_data_mod['Education'].unique()

array([0, 1], dtype=int64)

In [730]:
df_reason_data_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

### Final Checkpoint

In [731]:
df_preprocessed = df_reason_data_mod.copy()

In [732]:
df_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   
5         0         0         0         1 2015-07-10                     179   
6         0         0         0         1 2015-07-17                     361   
7         0         0         0         1 2015-07-24                     260   
8         0         0         1         0 2015-07-06                     155   
9         0         0         0         1 2015-07-13                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   
5                51   38                  239.554               31          0   
6                52   28                  239.554               27          0   
7                50   36                  239.554               23          0   
8                12   34                  239.554               25          0   
9                11   37                  239.554               29          1   

   Children  Pets  Absenteeism Time in Hours  Montth Value  Day of the Week  
0         2     1                          4             7                1  
1         1     0                          0             7                1  
2         0     0                          2             7                2  
3         2     0                          4             7                3  
4         2     1                          2             7                3  
5         0     0                          2             7                4  
6         1     4                          8             7                4  
7         4     0                          4             7                4  
8         2     0                         40             7                0  
9         1     1                          8             7                0

## Exporting The Data as a *.csv File

In [733]:
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False)